apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proxy-role
  namespace: system
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
