# permissions for end users to edit coderepoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coderepo-editor-role
  namespace: system
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoes/status
  verbs:
  - get
