---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - clusters
  - deploymentruntimes
  - environments
  - projectpipelineruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoes
  - coderepoproviders
  - products
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoes/finalizers
  verbs:
  - update
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoes/status
  verbs:
  - get
  - patch
  - update
