apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
          - name: ca
            mountPath: "/ca/ca.crt"
            subPath: ca.crt
            readOnly: true
          - name: client
            mountPath: "/ca/client.crt"
            subPath: client.crt
            readOnly: true
          - name: client
            mountPath: "/ca/client.key"
            subPath: client.key
            readOnly: true
      volumes:
        - name: ca
          secret:
            secretName: global-ca
        - name: client
          secret:
            secretName: cluster-keypair