apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-transform-rules
  namespace: system
data:
  k8s-secret.yaml: |
    providerType: operatorhub
    callerType: http
    resourceType: secret
    create:
      generation:
        request: POST
        body: |
          {
            "apiVersion": "v1",
            "kind": "Secret",
            "metadata": {
              "name": "{{ .Name }}"
            },
            "type": "Opaque",
            "data": {
              "password": "{{ .SensitiveSpec.password | base64Encode }}"
            }
          }
        uri: 'api/v1/namespaces/{{ .Space }}/secrets'
      parse:
      - name: spec
        path: .spec
    get:
      generation:
        request: GET
        uri: 'api/v1/namespaces/{{ .Space }}/secrets/{{ .Name }}'
      parse:
      - name: spec
        path: .spec
      parsePeer:
      - name: resourceVersion
        path: .metadata.resourceVersion
    update:
      generation:
        request: PUT
        body: |
          {
            "apiVersion": "v1",
            "kind": "Secret",
            "metadata": {
              "name": "{{ .Name }}",
              "resourceVersion": "{{ .Status.Peer.resourceVersion }}"
            },
            "type": "Opaque",
            "data": {
              "password": "{{ .SensitiveSpec.password | base64Encode }}"
            }
          }
     
        uri: '/api/v1/namespaces/{{ .Space }}/secrets/{{ .Name }}'
      parse:
      - name: spec
        path: .spec
    delete:
      generation:
        request: DELETE
        uri: 'api/v1/namespaces/{{ .Space }}/secrets/{{ .Name }}'
    
