apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-transform-rules
  namespace: system
data:
  k8s-service.yaml: | 
    providerType: operatorhub
    callerType: http
    resourceType: service
    create:
      generation:
        request: POST
        body: |
          {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
              "name": "{{ .Name }}"
            },
            "spec": {
              "selector": {
                "app": "{{ .Spec.selectValue }}"
              },
              {{ if .Spec.serviceType -}}
              "type": "{{ .Spec.serviceType }}",
              {{- end }}
              "ports": [
                {
                  "protocol": "TCP",
                  {{ if .Spec.exportPort -}}
                  "nodePort": {{ .Spec.exportPort }},
                  {{- end }}
                  "port": 6379,
                  "targetPort": 6379
                }
              ]
            }
          }
        uri: 'api/v1/namespaces/{{ .Space }}/services'
      parse:
      - name: spec
        path: .spec
    get:
      generation:
        request: GET
        uri: 'api/v1/namespaces/{{ .Space }}/services/{{ .Name }}'
      parse:
      - name: spec
        path: .spec
      parsePeer:
      - name: resourceVersion
        path: .metadata.resourceVersion
    update:
      generation:
        request: PUT
        body: |
          {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
              "name": "{{ .Name }}",
              "resourceVersion": "{{ .Status.Peer.resourceVersion }}"
            },
            "spec": {
              "selector": {
                "app": "{{ .Spec.selectValue }}"
              },
              {{ if .Spec.serviceType -}}
              "type": "{{ .Spec.serviceType }}",
              {{- end }}
              "ports": [
                {
                  "protocol": "TCP",
                  {{ if .Spec.exportPort -}}
                  "nodePort": {{ .Spec.exportPort }},
                  {{- end }}
                  "port": 6379,
                  "targetPort": 6379
                }
              ]
            }
          }
        uri: 'api/v1/namespaces/{{ .Space }}/services/{{ .Name }}'
      parse:
      - name: spec
        path: .spec
    delete:
      generation:
        request: DELETE
        uri: 'api/v1/namespaces/{{ .Space }}/services/{{ .Name }}'
    
