---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - argoproj.io
  resources:
  - appprojects
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - hnc.x-k8s.io
  resources:
  - hierarchyconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - artifactrepoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - artifactrepoproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - deploymentruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - deploymentruntimes/finalizers
  verbs:
  - update
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - deploymentruntimes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - environments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - products
  verbs:
  - get
  - list
  - watch
