# permissions for end users to view basedatasyncconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basedatasyncconfig-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - basedatasyncconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - basedatasyncconfigs/status
  verbs:
  - get
