# permissions for end users to edit basedatasyncconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basedatasyncconfig-editor-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - basedatasyncconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - basedatasyncconfigs/status
  verbs:
  - get
