apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautes
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ tenant_name }}
  source:
    path: nautes/overlays/tenant
    repoURL: {{ tenant_repo_ssh_addr }}
    targetRevision: HEAD
  ignoreDifferences:
  - kind: ConfigMap
    name: dex
    namespace: dex
    jsonPointers:
    - /data
  destination:
    server: https://kubernetes.default.svc
    namespace: nautes
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
