apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/crds/crd/bases/nautes.resource.nautes.io_clusters.yaml
- ../../base/crds/crd/bases/nautes.resource.nautes.io_coderepoes.yaml
- ../../base/argo-operator/default
- ../production/code-repos
namespace: nautes
