apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

namespace: {{ nautes_namespace }}

resources:
- ../../base/crd/bases/nautes.resource.nautes.io_clusters.yaml
- ../../base/crd/bases/nautes.resource.nautes.io_coderepoes.yaml
- ../../base/apps/overlays/argo-operator
- ../production/code-repos

patches:
- path: ../production/configmaps/global-cm.yaml
  target:
    kind: ConfigMap
    labelSelector: nautes-configs=true

images:
- name: controller
  newName: {{ nautes_image_name }}
  newTag: {{ image_version }}

