# permissions for end users to view enviroments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enviroment-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - enviroments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - enviroments/status
  verbs:
  - get
