# permissions for end users to edit enviroments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enviroment-editor-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - enviroments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - enviroments/status
  verbs:
  - get
