apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
          - name: vault-proxy-client
            mountPath: "/opt/nautes/keypair/client.crt"
            subPath: apiserver.crt
          - name: vault-proxy-client
            mountPath: "/opt/nautes/keypair/client.key"
            subPath: apiserver.key
      volumes:
        - name: vault-proxy-client
          secret:
            secretName: api-server-cert

