apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-server
  namespace: nautes
spec:
  rules:
  - host: "apiserver.192.168.75.130.nip.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-service
            port:
              name: http
