apiVersion: v1
kind: Secret
metadata:
  name: remote-certs
type: Opaque
data:
  {{ git_http_domain }}.crt: |
{{ git_ca | b64encode | indent( width=4, indentfirst=True) }}
  {{ vault_domain }}_{{ vault_port }}.crt: |
{{ sec_ca | b64encode | indent( width=4, indentfirst=True) }}
  {{ vault_domain }}_{{ vault_proxy_port }}.crt: |
{{ sec_ca | b64encode | indent( width=4, indentfirst=True) }}

