apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
          - name: remote-certs
            mountPath: "/opt/nautes/cert/"
      volumes:
        - name: remote-certs
          secret:
            secretName: remote-certs

