apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
          - name: vault-proxy-client
            mountPath: "/opt/nautes/keypair"
      volumes:
        - name: vault-proxy-client
          secret:
            secretName: cluster-keypair

