apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
          - name: ca
            mountPath: "/ca/ca.crt"
            subPath: ca.crt
            readOnly: true
          - name: vault-proxy-client
            mountPath: "/opt/nautes/keypair"
      volumes:
        - name: ca
          secret:
            secretName: global-ca
        - name: vault-proxy-client
          secret:
            secretName: runtime-keypair

