apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
          - name: ca
            mountPath: "/ca/ca.crt"
            subPath: ca.crt
            readOnly: true
          - name: vault-proxy-client
            mountPath: "/opt/nautes/keypair"
          - name: middleware-transform-rules
            mountPath: "/opt/nautes/middleware-transform-rules"
          - name: resource-transform-rules
            mountPath: "/opt/nautes/resource-transform-rules"
      volumes:
        - name: ca
          secret:
            secretName: global-ca
        - name: vault-proxy-client
          secret:
            secretName: runtime-keypair
        - name: middleware-transform-rules
          configMap:
            name: middleware-transform-rules
        - name: resource-transform-rules
          configMap:
            name: resource-transform-rules
