apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../cert-manager/overlays/production
- ../../dex/overlays/production
- ../../reloader/overlays/production
- ../../nautes/overlays/tenant

