apiVersion: v1
kind: ConfigMap
metadata:
  name: nautes-configs
data:
  config: |
    nautes:
      tenantName: "{{ tenant_name }}"
      namespace: "{{ nautes.namespace }}"
      runtimeTemplateSource: "{{ repos.cluster_template.url }}"
    OAuth:
      OAuthType: "dex"
      issuer: "{{ oauth_url }}"
      clientID: "nautes"
      clientSecret: "{{ dex_client_secret }}"
    git:
      addr: "{{ gitlab_external_url }}"
      gitType: gitlab
    secret:
      operatorName:
        Api: {{ nautes.secret_roles.api }}
        Argo: {{ nautes.secret_roles.argo }}
        Base: {{ nautes.secret_roles.base }}
        Cluster: {{ nautes.secret_roles.cluster }}
        Repo: {{ nautes.secret_roles.repo }}
        Runtime: {{ nautes.secret_roles.runtime }}
      vault:
        mountPath: "{{ tenant_name }}"
        addr: "{{ vault_url }}"
        proxyAddr: "{{ vault_proxy_url }}"
        CABundle: |
{{ ca_info | indent( width=10, indentfirst=True) }}
