apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: nautes
  labels:
    app: api-server
    app.kubernetes.io/name: api-server
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: api-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-server
  namespace: nautes
spec:
  rules:
  - host: "{{ nautes_api_server_domain }}"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-server
            port:
              name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: nautes
spec:
  selector:
    matchLabels:
      app: api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      serviceAccountName: api-server-manager
      containers:
      - name: api-server
        image: {{ api_server_image }}
        env:
        - name: RESOURCES_LAYOUT
          value: /usr/local/share/resources_layout.yaml
        lifecycle:
          postStart:
            exec:
              command:
                ['/bin/sh', "-c", 'update-ca-certificates']
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: api-server-secret
          mountPath: /usr/local/share/ca-certificates
        - name: resources-layout
          mountPath: /usr/local/share/
          readOnly: true
        - name: api-server-log
          mountPath: /log
      volumes:
      - name: resources-layout
        configMap:
          name: resources-layout
          items:
          - key: resources_layout.yaml
            path: resources_layout.yaml
      - name: api-server-secret
        projected:
          sources:
          - secret:
              name: api-server-cert
          - secret:
              name: api-server-gitlab-ca
      - name: api-server-log
        persistentVolumeClaim:
          claimName: api-server-log
