---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: nautes
spec:
  selector:
    matchLabels:
      app: api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      serviceAccountName: api-server-manager
      containers:
      - name: api-server
        image: {{ api_server_image }}
        env:
        - name: RESOURCES_LAYOUT
          value: /usr/local/share/resources_layout.yaml
        args:
          - /app/manager
          - -conf=/data/conf
          - -global-config-namespace={{ nautes_namespace }}
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  cp /opt/nautes/out/pki/ca.crt /usr/local/share/ca-certificates/
                  update-ca-certificates
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: api-server-secret
          mountPath: /opt/nautes/out/pki
        - name: resources-layout
          mountPath: /usr/local/share/
          readOnly: true
        - name: api-server-log
          mountPath: /log
        - name: nautes-tls-certs
          mountPath: /opt/nautes/ssl/
        - name: ca-certs
          mountPath: /usr/local/share/ca-certificates/
      volumes:
      - name: resources-layout
        configMap:
          name: resources-layout
          items:
          - key: resources_layout.yaml
            path: resources_layout.yaml
      - name: api-server-secret
        projected:
          sources:
          - secret:
              name: api-server-cert
          - secret:
              name: api-server-gitlab-ca
      - name: nautes-tls-certs
        configMap:
          name: nautes-tls-certs
      - name: api-server-log
        persistentVolumeClaim:
          claimName: api-server-log
      - name: ca-certs
        emptyDir: {}
