apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- api_server_manager_log_pvc.yaml
- deployment.yaml
- resources_layout.yaml
- role.yaml
- rolebinding.yaml
- service_account.yaml
- service.yaml
namespace: nautes
