apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: nautes
  labels:
    app: api-server
    app.kubernetes.io/name: api-server
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: api-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-server
  namespace: nautes
spec:
  rules:
  - host: "{{ nautes_api_server_domain }}"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-server
            port:
              name: http


