apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
        - name: configs
          mountPath: /opt/nautes/configs
      volumes:
      - name: configs
        configMap:
          name: nautes-configs